# Generated by Django 5.1.4 on 2025-11-21 23:57

import account.models
import django.core.validators
import django.utils.timezone
import re
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Obrigatório. 100 caractéres ou menos. Letras, números e @/./+/-/_ caractéres', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Enter a valid username.', 'invalid')], verbose_name='username')),
                ('first_name', models.CharField(max_length=30, verbose_name='Primeiro Nome')),
                ('walletId', models.CharField(blank=True, help_text='Vazio para nova subconta.', max_length=255, verbose_name='Wallet ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('login_email', models.EmailField(blank=True, help_text='Email de login para a conta Asaas.', max_length=255, null=True, verbose_name='Email de Login')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, validators=[account.models.validate_cpf_cnpj], verbose_name='CPF/CNPJ')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('company_type', models.CharField(blank=True, choices=[('MEI', 'MEI'), ('LIMITED', 'Limited'), ('INDIVIDUAL', 'Individual'), ('ASSOCIATION', 'Association')], max_length=20, null=True, verbose_name='Tipo da Empresa')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Fixo')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, validators=[account.models.validate_celular], verbose_name='Telefone Celular')),
                ('site', models.URLField(blank=True, max_length=255, null=True, verbose_name='Site')),
                ('income_value', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Faturamento/Renda Mensal')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Endereço')),
                ('address_number', models.CharField(max_length=10, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Membro da equipe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('fixedValue', models.DecimalField(blank=True, decimal_places=2, help_text='Valor da comissão fixa padrão do usuário.', max_digits=12, null=True, verbose_name='Comissão fixa (R$)')),
                ('percentualValue', models.DecimalField(blank=True, decimal_places=2, default=10.0, help_text='Valor da comissão percentual padrão do usuário.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comissão percentual')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group', verbose_name='Perfis')),
                ('pages_allowed', models.ManyToManyField(blank=True, related_name='user_pages_allowed', to='pages.page', verbose_name='Páginas autorizadas')),
                ('subpages_allowed', models.ManyToManyField(blank=True, related_name='user_subpages_allowed', to='pages.subpage', verbose_name='Subpáginas autorizadas')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissões específicas para este usuário.', related_name='user_permissions', to='auth.permission', verbose_name='Permissões do usuário')),
            ],
            options={
                'verbose_name': 'Subconta',
                'ordering': ['email'],
                'permissions': [('can_edit_own_account', 'Pode editar apenas a própria conta')],
                'indexes': [models.Index(fields=['email'], name='account_use_email_553b8f_idx')],
            },
        ),
    ]
