# Generated by Django 5.1.4 on 2025-11-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='walletId',
            field=models.CharField(blank=True, help_text='Vazio para novo afiliado.', max_length=255, verbose_name='Wallet ID'),
        ),
    ]
