# Generated by Django 5.1.4 on 2025-04-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_profiles_alter_user_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'permissions': [('can_edit_own_account', 'Pode editar apenas a própria conta')], 'verbose_name': 'Subconta'},
        ),
    ]
