# Generated by Django 5.1.4 on 2025-04-18 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 18, 21, 47, 23, 462606, tzinfo=datetime.timezone.utc), verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
    ]
