# Generated by Django 5.1.4 on 2025-04-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_type',
            field=models.CharField(choices=[('MEI', 'MEI'), ('LIMITED', 'Limited'), ('INDIVIDUAL', 'Individual'), ('ASSOCIATION', 'Association')], default='MEI', max_length=20, verbose_name='Tipo da Empresa'),
            preserve_default=False,
        ),
    ]
