# Generated by Django 5.1.4 on 2025-04-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_type',
            field=models.CharField(blank=True, choices=[('MEI', 'MEI'), ('LIMITED', 'Limited'), ('INDIVIDUAL', 'Individual'), ('ASSOCIATION', 'Association')], max_length=20, null=True, verbose_name='Tipo da Empresa'),
        ),
    ]
