# Generated by Django 5.1.4 on 2025-11-21 23:57

import billings.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('billingType', models.CharField(blank=True, choices=[('CREDIT_CARD', 'Crédito'), ('BOLETO', 'Boleto'), ('PIX', 'PIX')], max_length=20, null=True, verbose_name='Forma de pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dueDate', models.DateField(default=billings.models.get_due_date, verbose_name='Data de vencimento')),
                ('paylink', models.URLField(editable=False, null=True, verbose_name='Link de pagamento')),
                ('asaasId', models.CharField(editable=False, max_length=255, null=True, verbose_name='ID Asaas')),
                ('installmentCount', models.IntegerField(help_text='Somente no caso de cobrança parcelada.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='Número de parcelas')),
                ('value', models.DecimalField(decimal_places=2, help_text='Informe o valor total da cobrança em reais (R$). Exemplo: 99.90', max_digits=12, verbose_name='Valor da cobrança')),
                ('successUrl', models.URLField(blank=True, help_text='URL para a qual o cliente será redirecionado após o pagamento bem-sucedido da fatura ou link de pagamento.', null=True, verbose_name='URL')),
                ('autoRedirect', models.BooleanField(default=False, help_text='Define se o redirecionamento será automático após o pagamento. Se falso, o cliente verá um botão para retornar manualmente.', verbose_name='Auto redirecionamento')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_billings', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_links', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cobrança',
            },
        ),
        migrations.CreateModel(
            name='BillingSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixedValue', models.DecimalField(blank=True, decimal_places=2, help_text='Valor da comissão fixa padrão do usuário.', max_digits=12, null=True, verbose_name='Comissão fixa (R$)')),
                ('percentualValue', models.DecimalField(blank=True, decimal_places=2, default=10.0, help_text='Valor da comissão percentual padrão do usuário.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comissão percentual')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='billings.billing', verbose_name='Link de pagamento')),
                ('subaccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subaccount', to=settings.AUTH_USER_MODEL, verbose_name='Subconta')),
            ],
            options={
                'verbose_name': 'Subconta',
                'verbose_name_plural': 'Subcontas',
                'ordering': ['subaccount__first_name'],
            },
        ),
    ]
