# Generated by Django 5.1.4 on 2025-11-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='installmentCount',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], help_text='Somente no caso de cobrança parcelada.', null=True, verbose_name='Número de parcelas'),
        ),
    ]
