# Generated by Django 5.1.4 on 2025-04-09 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='billingsplit',
            name='fixedValue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor da comissão fixa padrão do usuário.', max_digits=12, null=True, verbose_name='Comissão fixa (R$)'),
        ),
    ]
