# Generated by Django 5.1.4 on 2025-04-09 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_billing_created_by_alter_billingsplit_fixedvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
