# Generated by Django 5.1.4 on 2025-11-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_alter_billing_installmentcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='status',
            field=models.CharField(default='Criada', editable=False, max_length=50, verbose_name='Status'),
        ),
    ]
