# Generated by Django 5.1.4 on 2025-04-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0003_billing_created_at_billing_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
