# Generated by Django 5.1.4 on 2025-04-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0004_alter_billing_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='created_by',
        ),
    ]
