# Generated by Django 5.1.4 on 2025-11-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0004_alter_billing_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='discount_dueDateLimitDays',
            field=models.IntegerField(blank=True, help_text='Dias antes do vencimento para aplicar o desconto (0 = até o vencimento).', null=True, verbose_name='Dias limite para aplicar desconto'),
        ),
        migrations.AddField(
            model_name='billing',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentual'), ('FIXED', 'Fixo')], max_length=20, null=True, verbose_name='Tipo de desconto'),
        ),
        migrations.AddField(
            model_name='billing',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor percentual ou fixo do desconto.', max_digits=12, null=True, verbose_name='Valor do desconto'),
        ),
    ]
