# Generated by Django 5.1.4 on 2025-04-10 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0005_remove_billing_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingsplit',
            options={'ordering': ['subaccount__first_name'], 'verbose_name': 'Subconta', 'verbose_name_plural': 'Subcontas'},
        ),
        migrations.AlterField(
            model_name='billingsplit',
            name='billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='billings.billing', verbose_name='Link de pagamento'),
        ),
    ]
