# Generated by Django 5.1.4 on 2025-11-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0005_billing_discount_duedatelimitdays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='interest_enabled',
            field=models.BooleanField(default=False, help_text='Habilitar juros'),
        ),
        migrations.AddField(
            model_name='billing',
            name='interest_start_after_days',
            field=models.PositiveIntegerField(blank=True, help_text='Dias após o vencimento para começar a cobrar juros', null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='interest_type',
            field=models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentual (%)'), ('FIXED', 'Valor Fixo')], help_text='Tipo de juros', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='interest_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do juros (em % ou R$ dependendo do tipo)', max_digits=10, null=True),
        ),
    ]
