# Generated by Django 5.1.4 on 2025-11-23 18:46

import billings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0006_billing_interest_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='dueDate',
            field=models.DateField(default=billings.models.get_due_date, help_text='Data de vencimento da cobrança. No caso de cobrança parcelada, esta data será usada apenas como vencimento da primeira parcela. As demais parcelas terão sua data calculada automaticamente pelo Asaas, mês a mês.', verbose_name='Data de vencimento'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='interest_enabled',
            field=models.BooleanField(default=False, help_text='Ativa a cobrança de juros após o vencimento.', verbose_name='Habilitar juros'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='interest_start_after_days',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade de dias após o vencimento para começar a cobrar os juros.', null=True, verbose_name='Início da cobrança (dias)'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='interest_type',
            field=models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentual (%)'), ('FIXED', 'Valor Fixo')], help_text='Define se os juros serão percentuais ou um valor fixo.', max_length=20, null=True, verbose_name='Tipo de juros'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='interest_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor dos juros (em % ou R$, dependendo do tipo selecionado).', max_digits=10, null=True, verbose_name='Valor do juros'),
        ),
    ]
