# Generated by Django 5.1.4 on 2025-11-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0007_alter_billing_duedate_alter_billing_interest_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='daysAfterDueDateToRegistrationCancellation',
            field=models.PositiveIntegerField(blank=True, help_text='Dias após o vencimento para cancelamento automático do registro (somente para boletos bancários).', null=True, verbose_name='Dias para cancelamento do registro'),
        ),
        migrations.AddField(
            model_name='billing',
            name='fine_enabled',
            field=models.BooleanField(default=False, help_text='Ativa a cobrança de multa para pagamentos após o vencimento.', verbose_name='Habilitar multa'),
        ),
        migrations.AddField(
            model_name='billing',
            name='fine_type',
            field=models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentual (%)'), ('FIXED', 'Valor Fixo (R$)')], help_text='Define se a multa será percentual ou um valor fixo.', max_length=20, null=True, verbose_name='Tipo de multa'),
        ),
        migrations.AddField(
            model_name='billing',
            name='fine_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor da multa (em % ou em R$, conforme o tipo selecionado).', max_digits=10, null=True, verbose_name='Valor da multa'),
        ),
    ]
