# Generated by Django 5.1.4 on 2025-11-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0008_billing_daysafterduedatetoregistrationcancellation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='description',
            field=models.CharField(blank=True, help_text='Descrição da cobrança (máx. 500 caracteres).', max_length=500, null=True, verbose_name='Descrição'),
        ),
    ]
