# Generated by Django 5.1.4 on 2025-11-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0009_billing_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='interest_type',
        ),
        migrations.AlterField(
            model_name='billing',
            name='interest_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor dos juros (%).', max_digits=10, null=True, verbose_name='Valor do juros'),
        ),
    ]
