# Generated by Django 5.1.4 on 2025-11-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0010_remove_billing_interest_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='interest_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do juros (%)'),
        ),
    ]
