# Generated by Django 5.1.4 on 2025-11-25 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0011_alter_billing_interest_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='asaasId',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='paylink',
        ),
    ]
