# Generated by Django 5.1.4 on 2025-04-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='app_related',
            field=models.CharField(default='', max_length=100, verbose_name='Aplicativo relacionado'),
            preserve_default=False,
        ),
    ]
