# Generated by Django 5.1.4 on 2025-11-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True, verbose_name='CPF/CNPJ')),
                ('asaasId', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Asaas ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('address_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='cep')),
                ('additional_emails', models.TextField(blank=True, help_text='Emails separados por vírgula', null=True, verbose_name='Emails adicionais')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('foreign_customer', models.BooleanField(default=False, verbose_name='Cliente estrangeiro?')),
            ],
        ),
    ]
