# Generated by Django 5.1.4 on 2025-11-26 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfiliadoAsaas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalId', models.CharField(editable=False, max_length=255, null=True, verbose_name='ID Asaas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asaas_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração Asaas do Afiliado',
                'verbose_name_plural': 'Configurações Asaas dos Afiliados',
                'unique_together': {('afiliado',)},
            },
        ),
    ]
