# Generated by Django 5.1.4 on 2025-11-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afiliadoasaas',
            options={'verbose_name': 'Configuração Asaas do Afiliado', 'verbose_name_plural': 'Configuração Asaas dos Afiliados'},
        ),
        migrations.AlterField(
            model_name='afiliadoasaas',
            name='externalId',
            field=models.CharField(max_length=255, null=True, verbose_name='ID Asaas'),
        ),
    ]
