# Generated by Django 5.1.4 on 2025-11-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas', '0002_alter_afiliadoasaas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliadoasaas',
            name='externalId',
            field=models.CharField(max_length=255, null=True, verbose_name='Identificador da carteira (Wallet ID)'),
        ),
    ]
