# Generated by Django 5.1.4 on 2025-11-27 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas', '0003_alter_afiliadoasaas_externalid'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsaasConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_api', models.CharField(max_length=255)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asaas_config', to='integrations.integration')),
            ],
        ),
    ]
