# Generated by Django 5.1.4 on 2025-11-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas', '0004_asaasconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asaasconfig',
            name='token_api',
        ),
        migrations.AddField(
            model_name='asaasconfig',
            name='token_api_encrypted',
            field=models.TextField(blank=True, null=True, verbose_name='Token API criptografado'),
        ),
    ]
