# Generated by Django 5.1.4 on 2025-11-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas', '0005_remove_asaasconfig_token_api_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asaasconfig',
            name='token_api_encrypted',
        ),
        migrations.AddField(
            model_name='asaasconfig',
            name='token_api',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token API'),
        ),
    ]
