# Generated by Django 5.1.4 on 2025-12-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas', '0006_remove_asaasconfig_token_api_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asaasconfig',
            name='status',
            field=models.CharField(choices=[('não_configurado', 'Não configurado'), ('aguardando_teste', 'Aguardando teste'), ('conectado', 'Conectado'), ('token_inválido', 'Token inválido'), ('erro_de_conexao', 'Erro de conexão'), ('api_indisponível', 'API indisponível'), ('erro_desconhecido', 'Erro desconhecido')], default='não_configurado', editable=False, max_length=50),
        ),
    ]
