# Generated by Django 5.1.4 on 2025-12-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas', '0008_alter_asaasconfig_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliadoasaas',
            name='status',
            field=models.CharField(choices=[('nao_configurado', 'Não configurado'), ('aguardando_teste', 'Aguardando teste'), ('conectado', 'Conectado'), ('token_invalido', 'Token inválido'), ('erro_de_conexao', 'Erro de conexão'), ('api_indisponivel', 'API indisponível'), ('erro_desconhecido', 'Erro desconhecido')], default='não_configurado', editable=False, max_length=50),
        ),
    ]
