# Generated by Django 5.1.4 on 2025-12-09 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integration',
            options={'verbose_name': 'Integrações do Sistema', 'verbose_name_plural': 'Integrações do Sistema'},
        ),
    ]
